### ISSUE TITLE
Synchronised Watchers

### ISSUE THREAD

**Issue by mhussa** [ninibe/netlog#8]
Thankyou for open sourcing this project very useful.

I have a use case which requires that I only handle messages which have been persisted to disk.  From reading the code I could see how changes to the index trigger a notification but no indication that the notified update is in sync.

Can you clarify how this works? (in case I've missed something).  Is there a small window where a message could be lost if the process dies and hasn't flushed to disk but *has* notified a watcher about the new message?

**Comment by bictorman** [comment]
Hi mhussa,

First of all, **don't use netlog in production yet**! specially not if you have strict data safety requirements.

Now, if we overlook that for the sake of argument, this is a complicated issue. The system is currently low guarantees. I mean, right now it's single node so if you lose the server you lose all your data. But I'll assume you would be running it in some sort of HA storage.

If by flush you mean [flushing a batch](https://github.com/ninibe/netlog/blob/b063449900867399171143ae2b0f60f326288e17/message_buffer.go#L58), the client will not get notified until the entire batch has been written, since the batching happens in netlog and the notification and data reads comes from biglog underneath.

If by flush you mean [fsync](https://github.com/ninibe/netlog/blob/b063449900867399171143ae2b0f60f326288e17/biglog/segment.go#L307), then I'm not an expert in file systems but it's my understanding that nothing gets lost just because the process dies, you would need the whole OS to go down to lose data.

To hypothetically overcome the latter with watchers it would not be a good idea, because while you can control to notify the watcher after calling sync() you can't control that further data has not been again "half-written" afterwards and the reader will try get it. Watchers only notify if something has been written since the last time, they don't keep a separate signal for every write made, so readers will read until EOF and you can't stop them.

So currently it's not possible to have those guarantees, in the future I see 2 possible solutions. 

One would be to add a setting to open the biglogs in sync mode, meaning open the data file with O_SYNC and add facilities to rebuild the index at boot if something went wrong. Although that would severely hinder performance.

Another one, once replication is implemented, would simply be to write data to the leader and read it from the follower.

**Comment by mhussa** [comment]
> First of all, don't use netlog in production yet! specially not if you have strict data safety requirements.

:) a reminder to anyone investigating at this stage is always good.  At the moment I'm using a WAL based key/val store but would like a persistent log with kafka-esque performance without its management overhead.

I really meant fsync:

1. http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/
2. https://lwn.net/Articles/457667/

Losing an OS is not entirely inconceivable in the case of a power outage.  I expect the worst and hope for the best.

I agree a synchronised file descriptor approach with O_SYNC would really sap performance and the actual fsync behaviour behaves differently on different platforms and variants of linux filesystems.

The kafka [docs](https://kafka.apache.org/08/ops.html
) indicate a preference for replication, see **6.4 Hardware and OS**.

I can't offer an alternative because as you mentioned it is a complicated issue.  I'll keep on eye on the project and will have a play with the replication stuff if/when you add it.  Thanks.

**Comment by bictorman** [comment]
Interesting read, looks like we should make some adjustments when creating new segments to ensure they don't get lost. thanks.

I'll ping you here when there's some replication working.
